# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master


pool:
  vmImage: 'ubuntu-16.04'


variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet restore

- task: DotNetCoreCLI@2
  displayName: 'Install dotnetsay'
  inputs:
    command: custom
    #projects: '**/*.csproj'
    custom: tool
    arguments: 'install -g dotnetsay'
    
- task: AzureRmWebAppDeployment@3
  inputs:
    azureSubscription: 'e0d55a0c-82b6-48a5-a957-dc70ede1f429'
    WebAppName: 'Bens Web App'
    Package: $(System.ArtifactsDirectory)/**/*.zip
